name: R-CMD-check
 
on: [push, pull_request]
 
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: macos-latest, r: 'release' }
          - { os: ubuntu-latest, r: 'devel' }
          - { os: ubuntu-latest, r: 'release' }
          - { os: ubuntu-latest, r: 'oldrel' }
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
 
    - name: Install dependencies
      run: |
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
        install.packages(c('lintr', 'testthat'))
    - name: Lint the package
      run: Rscript -e "lintr::lint_package()"
 
    - name: Check the package
      run: R CMD check --no-manual --as-cran